#ifndef IDT_ENUM_HPP
#define IDT_ENUM_HPP

struct IDTException {
	enum {
		DIVISION_BY_ZERO,
		SINGLE_STEP_INTERRUPT,
		NMI,
		BREAKPOINT,
		OVERFLOW,
		BOUNDS,
		INVALID_OPCODE,
		COPROCESSOR_NOT_AVAILABLE,
		DOUBLE_FAULT,
		COPROCESSOR_SEGMENT_OVERRUN,
		INVALID_TSS,
		SEGMENT_NOT_PRESENT,
		STACK_FAULT,
		GENERAL_PROTECTION_FAULT,
		PAGE_FAULT,
		RESERVED,
		MATH_FAULT,
		ALIGNMENT_CHECK,
		MACHINE_CHECK,
		SIMD_EXCEPTION,
		VIRTUALIZATION_EXCEPTION,
		CONTROL_PROTECTION_EXCEPTION
	};
};

#endif
